### PR TITLE
Add message for Windows users and add build instructions to readme

### PR DESCRIPTION
**Pull request by WesleyBryie**
I cannot get this to build on my machine, but I believe that it was a preexisting issue. All I did was add the warning message directed to windows users. If someone could look this over to see if it works or if another route needs to be taken, it would be appreciated...

### CODE REVIEW

**Comment by WesleyBryie** [comment]
Of course, the netlify build is going to fail because its trying to use an outdated version of node and its using NPM, but it works on my machine

**Comment by WesleyBryie** [comment]
@nythepegasus @Spidy123222 

Would appreciate a review.

**Comment by WesleyBryie** [comment]
Blustik told me that SideServer on Mac also is not stable and should not be used. If this is the case, why not just add another button next to the wiki button (`Install Instructions`) and comment out or remove the SideStore section?

**Comment by Spidy123222** [comment]
Since we've talked in GitHub about building the site. I think it would be best to just have a altserver section on the main page and have it as the default while sideserver has its problems.

**Comment by WesleyBryie** [comment]
Superseded by #37

**Pull request closed without merging**
