### PR TITLE
Updated Instructions

### PR DESCRIPTION
**Pull request by deformedRat**
Hi :3

Updated all instances of the word "SideStore" to be properly capitalized
Fixed typos and grammar mistakes (that **I** probably made)
Made additions to Pairing File instructions to cover some common issues some people encountered while making one
Rearranged Sideloading SideStore instructions to improve readability
Retitled instruction categories for clarity

### CODE REVIEW

**Comment by deformedRat** [comment]
Thought I forgot to do something but I didn't, whoops

**Review by WesleyBryie — CHANGES_REQUESTED** [review]
1. Enabling Developer Mode comes before trusting yourself as a dev
2. Repetitive text may look like it shouldn't be there in the code, however it should be. Depending on OS used, it will choose the proper string from the list (iirc Windows is first, macOS is second, linux is third), so repetitive text is not actually repetitive.

**Comment by deformedRat** [comment]
@WesleyBryie 
1. The order doesn't actually matter; activating developer mode just allows you to open the app, you can still verify the app before you activate it. I think it'd improve clarity by having activating developer mode be the last step, as people may assume that all the steps below are only for ios 16, which could cause frustration.
2. I'm aware, I don't believe I got rid of any. I just moved some of the "repeated text" to **before** to simplify the code (The parts that are the exact same on both). I can still change it back if it bothers you, though

**Review by WesleyBryie — APPROVED** [review]
Your response made sense. I apologize if I sounded rude in my review.

**Comment by deformedRat** [comment]
Nope, totally fine! i didn’t even detect any rudeness, just being formal 👍

**Pull request merged**
